<?php

/**
 * @file
 * Contains aa_search.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for simple_search_api_form.
 *
 * Removes the parameters 'form_build_id' and 'form_id' from the url.
 */
function aa_search_form_simple_search_api_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter() for complex_search_api_form.
 *
 * Removes the parameters 'form_build_id' and 'form_id' from the url.
 */
function aa_search_form_complex_search_api_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Implements hook_views_post_render().
 *
 * Rewrites the page title of taxonomy term search pages.
 */
function aa_search_views_post_render($view) {
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteName() === "entity.taxonomy_term.canonical") {
    $term = $route_match->getParameter("taxonomy_term");
    $term_name = $term->name->value;

    $title = NULL;
    if ($term->bundle() === "series") {
      $title = $term_name;
    } elseif (in_array($term->bundle(), ["author", "reader", "cover_artist"])) {
      $bundle = ucwords(str_replace("_", " ", $term->bundle()));
      $title = "Search works in: $term_name ($bundle)";
    } else {
      $title = "Search works in: $term_name";
    }

    if ($title !== NULL) {
      $view->setTitle($title);

      $route = $route_match->getCurrentRouteMatch()->getRouteObject();
      $route->setDefault("_title", $title);
      $route->setDefault('_title_callback', NULL);
    }
  }
}

/**
 * Implements template_preprocess_page_title().
 *
 * Sets the page title to NULL on legacy series search pages.
 */
function aa_search_preprocess_page_title(&$variables) {
  $route_match = \Drupal::routeMatch();
  if (array_key_exists('title', $variables) and
      is_array($variables['title']) and
      array_key_exists('#markup', $variables['title']) and
      $route_match->getRouteName() === "entity.taxonomy_term.canonical"
    ) {
    $term = $route_match->getParameter("taxonomy_term");

    if ($term->bundle() == "series") {
      $variables['title'] = NULL;
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Alters search forms so that:
 * - Widgets that need specific styling have an attribute to flag them
 * for twig suggestion alteration.
 * - The duration widgets are placed inside a fieldset.
 */
function aa_search_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (str_starts_with($form['#id'], 'views-exposed-form-search')) {
    foreach ([
      'search_api_fulltext', 'fandom', 'fandom-exclude', 'relationship',
      'relationship-exclude', 'reader', 'reader-exclude', 'author', 'author-exclude',
      'duration-from', 'duration-to', 'title',
    ] as $key) {
      $form[$key]['#attributes']['data_twig_suggestion'] = 'search';
    }

    $form['actions']['submit']['#attributes']['data_twig_suggestion'] = 'search';
    $form['actions']['reset']['#attributes']['data_twig_suggestion'] = 'search';
    $form['sort_by']['#attributes']['data_twig_suggestion'] = 'search';
    $form['sort_bef_combine']['#attributes']['data_twig_suggestion'] = 'search';

    $form['duration_fieldset'] = [
      '#type' => 'fieldset',
      '#name' => 'filter_duration_fieldset',
      '#title' => t('Filter Duration'),
      'duration-from' => $form['duration-from'],
      'duration-to' => $form['duration-to'],
    ];

    unset($form['duration-from']);
    unset($form['duration-to']);

    $form['#attached']['library'][] = 'aa_search/duration';
    $form['#attached']['library'][] = 'aa_search/search-sidebar';
    $form['#attached']['library'][] = 'aa_search/jump-to-filters';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for input.
 *
 * Alter twig suggestions for specific input widgets, to allow for form
 * specific templates.
 */
function aa_search_theme_suggestions_input_alter(&$suggestions, array $variables, $hook) {
  $element = $variables['element'];

  if (isset($element['#attributes']['data_twig_suggestion'])) {
    $suggestions[] = $hook . '__' . $element['#type'] . '__' . $element['#attributes']['data_twig_suggestion'];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form_element.
 *
 * Alter twig suggestions for specific form elements, to allow for form
 * specific templates.
 */
function aa_search_theme_suggestions_form_element_alter(array &$suggestions, array $variables, $hook) {
  $element = $variables['element'];

  if (isset($element['#attributes']['data_twig_suggestion'])) {
    $suggestions[] = $hook . '__' . $element['#attributes']['data_twig_suggestion'];
  }
}

/**
 * Implements hook_preprocess_fieldset().
 *
 * Allows twig templates to know whether a fieldset contains user-input
 * so that they can be expanded by default.
 */
function aa_search_preprocess_fieldset(&$variables) {
  if (isset($variables["element"]["#name"])) {
    $variables["fieldset_name"] = str_replace("_", "-", $variables["element"]["#name"]);
  }
  $variables["selection_made"] = !empty($variables["element"]["#value"]);

  if (isset($variables["fieldset_name"]) && $variables['fieldset_name'] === 'filter-duration-fieldset') {
    if (!empty($variables['element']['duration-from']['#value']) ||
        !empty($variables['element']['duration-to']['#value'])
    ) {
      $variables["selection_made"] = TRUE;
    }
  }
}

/**
 * Implements template_preprocess_input().
 *
 * Splits seconds into HH:MM:SS for the search duration widgets.
 */
function aa_search_preprocess_input(&$variables) {
  if (isset($variables['element']['#id'])) {
    if (in_array($variables['element']['#id'], ['edit-duration-from--2', 'edit-duration-to--2'])) {
      $total_seconds = $variables['element']['#value'];
      if ($total_seconds !== "") {
        $total_seconds = (int) $total_seconds;
        $variables["hours"] = str_pad(floor($total_seconds / 3600), 2, "0", STR_PAD_LEFT);
        $variables["mins"] = str_pad(floor(floor($total_seconds / 60) % 60), 2, "0", STR_PAD_LEFT);
        $variables["seconds"] = str_pad($total_seconds % 60, 2, "0", STR_PAD_LEFT);
      }
    }
  }
}

/**
 * Implements template_preprocess_views_view().
 *
 * Collects additional data needed for search views.
 */
function aa_search_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  if ($view->id() != 'search') {
    return;
  }

  $entities = array_map(fn($result) => $result->_entity, $view->result);
  $variables['total_nsfw'] = $utils->getTotalNsfw($entities);

  $current_uri = \Drupal::request()->getRequestUri();
  $url_sections = explode("?", $current_uri);
  $url_path = $url_sections[0];
  // Remove trailing forwards slash, if present.
  $url_path = substr($url_path, -1) === "/" ? substr($url_path, 0, strlen($url_path) - 1) : $url_path;
  $url_query = implode("?", array_slice($url_sections, 1, count($url_sections)));

  if ($view->current_display === "search_taxonomy") {
    $arguments = $variables['view']->argument;
    $tid = reset($arguments)->argument;

    $term = !empty($tid) ? \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid) : NULL;
    if (!empty($term)) {
      $variables['rss_feed'] = "/taxonomy/term/$tid/rss.xml?$url_query";
      $variables['taxonomy_term'] = $term;
      if ($term->parent->target_id !== 0) {
        $variables['term_parent'] = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($term->parent->target_id);
      }
      $variables['term_children'] = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree(
        $term->bundle(), $term->id(), NULL, TRUE);

      if (in_array($term->bundle(), ["author", "reader", "cover_artist"])) {
        $user_ids = \Drupal::entityQuery('user')
          ->condition("field_{$term->bundle()}_name.entity:taxonomy_term.tid", $term->id())
          ->accessCheck(TRUE)
          ->execute();
        $users = \Drupal::entityTypeManager()->getStorage('user')->loadMultiple($user_ids);

        $variables['user'] = NULL;
        if (!empty($users)) {
          $user = reset($users);
          $variables['user'] = $user;
          $psudonyms = [];

          foreach (["author", "reader", "cover_artist"] as $bundle) {
            if ($term->bundle() === $bundle) {
              continue;
            }

            $data = $user->get("field_{$bundle}_name")->referencedEntities();
            if (!empty($data)) {
              $psudonyms[] = $data[0];
            }
          }

          $variables["psudonyms"] = $psudonyms;
        }
      }

      if ($term->bundle() == "series") {
        // Need to do my own query to get legacy series metadata, because
        // the view results could be filtered!
        $series_work_ids = \Drupal::entityQuery('node')
          ->condition('type', 'legacy_work')
          ->condition('field_legacy_series.entity:taxonomy_term.tid', $term->id())
          ->sort('created', 'ASC')
          ->accessCheck(TRUE)
          ->execute();
        $series_works = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($series_work_ids);

        $authors = [];
        $readers = [];
        $languages = [];
        $all_tags = [];

        foreach ($series_works as $work) {
          $utils->fetchVocabTerms($work, 'field_author', $authors);
          $utils->fetchVocabTerms($work, 'field_reader', $readers);
          $utils->fetchVocabTerms($work, 'field_language', $languages);

          foreach (["field_fandom2", "field_relationship", "field_warning", "field_category", "field_format"] as $key) {
            $utils->fetchVocabTerms($work, $key, $all_tags);
          }
        }

        $variables['authors'] = $utils->removeDuplicateEntities($authors);
        $variables['readers'] = $utils->removeDuplicateEntities($readers);
        $variables['languages'] = $utils->removeDuplicateEntities($languages);
        $variables['all_tags'] = $utils->removeDuplicateEntities($all_tags);

        $date_formatter = \Drupal::service('date.formatter');

        $first_work = reset($series_works);
        if (!empty($first_work)) {
          $created_date = $date_formatter->format($first_work->getCreatedTime(), "custom", "j F Y");
          $variables['created_at'] = $created_date;
        }

        $updated_date = $date_formatter->format($term->getChangedTime(), "custom", "j F Y");
        $variables['updated_at'] = $updated_date;
      }
    }
  } elseif (in_array($view->current_display, ["search", "search_collection"])) {
    $variables['rss_feed'] = "$url_path/rss.xml?$url_query";
  }
}
