<?php

/**
 * @file
 * Contains series_part_label_validation.module.
 */

use Drupal\Core\Entity\ContentEntityType;

/**
 * Implements hook_entity_bundle_field_info_alter() for Works.
 *
 * Adds a validator to ensure that if a series is linked, a part label must be defined.
 */
function series_part_label_validation_entity_bundle_field_info_alter(
  array &$fields, ContentEntityType $entity_type, $bundle
) {
    if (
      $entity_type->id() === "node" &&
      $bundle === "work" &&
      isset($fields['field_part_label']
    )) {
      $fields['field_part_label']->addConstraint('NotEmptyWhenPartOfSeries', []);
    }
}