<?php
/**
 * @file
 * Install, update and uninstall functions for the custom module.
 */

use Drupal\user\Entity\Role;

/**
 * Removes the 'flag to_listen' permission from all roles.
 */
function remove_flag_update_8001() {
  $all_roles = Role::loadMultiple();
  foreach ($all_roles as $role) {
    if ($role->hasPermission('flag to_listen')) {
      $role->revokePermission('flag to_listen');
      $role->save();
    }
  }
}