access_by_ref.abrconfig.*:
  type: config_entity
  label: 'Access by ref config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    bundle:
      type: string
      label: 'Bundle'
    field:
      type: string
      label: 'Reference field'
    reference_type:
      type: string
      label: 'Reference type'
    extra:
      type: string
      label: 'Extra field'
    rights_type:
      type: string
      label: 'Rights type'
    rights_read:
      type: boolean
      label: 'Read rights'
    rights_update:
      type: boolean
      label: 'Update rights'
    rights_delete:
      type: boolean
      label: 'Delete rights'
