<?php

/**
 * @file
 * Contains search_api_blocks.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Removes the parameters 'form_build_id' and 'form_id' from the url.
 */
function search_api_blocks_form_simple_search_api_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}
