<?php

use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_form_alter().
 */
function audiofic_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_work_form') {
    // Attach the JavaScript to the form.
    $form['#attached']['library'][] = 'audiofic/audiofic_styles';
  }
}

/**
 * Implements hook_node_access().
 */
function audiofic_node_access(NodeInterface $node, $operation, AccountInterface $account) {

  if (($operation == 'update' || $operation == 'delete') && $node->getType() == 'work') {
    $user = \Drupal\user\Entity\User::load($account->id());

    if ($user->hasField('field_reader_name') && !$user->get('field_reader_name')->isEmpty()) {
      $user_reader_name_entity = $user->get('field_reader_name')->first()->entity;
    } else {
      return \Drupal\Core\Access\AccessResult::neutral();
    }

    if ($node->hasField('field_reader') && !$node->get('field_reader')->isEmpty()) {
      $node_reader_entity = $node->get('field_reader')->first()->entity;
    } else {
      return \Drupal\Core\Access\AccessResult::neutral();
    }

    $access = \Drupal\Core\Access\AccessResult::forbiddenIf(
      $user_reader_name_entity->id() != $node_reader_entity->id(),
      'The user\'s reader name entity does not match the node\'s reader entity.'
    );

    //Make sure the access result is cacheable per user and per node.
    $access->addCacheableDependency($user);
    $access->addCacheableDependency($node);

    return $access;
  }

  return \Drupal\Core\Access\AccessResult::neutral();
}