<?php

/**
 * @file
 * Contains propogate_metadata.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;
use Drupal\Core\Entity\Query\QueryInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_form_alter().
 */
function propagate_metadata_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Prefill reader field on node creation.
  $reader_name = propagate_metadata_get_user_tag('field_reader_name');
  if ($reader_name !== NULL and
      in_array($form_id, ['node_work_form', 'node_playlist_form'])
    ) {
    propagate_metadata_fill_default_form_value($form, 'field_reader', $reader_name);
    propagate_metadata_fill_default_form_value($form, 'field_owner', $reader_name);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for nodes.
 */
function propagate_metadata_node_presave(NodeInterface $node) {
  if ($node->getType() === "work") {
    $duration = propagate_metadata_set_duration($node);
    propagate_metadata_update_all_collections($node, updated_duration_seconds: $duration);
  }

  if ($node->getType() === "legacy_work") {
    propagate_metadata_update_all_collections($node);
  }

  if ($node->getType() === "playlist") {
    // Only update series metadata if a work is added/removed.
    // Otherwise correct metadata will be overwritten.
    if (is_null($node->original)) {
      return;
    }

    $old_work_arr = $node->original->get('field_works_series');
    $new_work_arr = $node->get('field_works_series');

    if (count($old_work_arr) == count($new_work_arr)) {
      return;
    }

    /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
    $utils = \Drupal::service('aa_utils.utils');

    $works = $new_work_arr->referencedEntities();
    $utils->setCollectionMetadata($node, $works, save: FALSE);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for nodes.
 */
function propagate_metadata_node_delete(NodeInterface $node) {
  if (in_array($node->getType(), ["work", "legacy_work"])) {
    propagate_metadata_update_all_collections($node, work_deleted: TRUE);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for users.
 */
function propagate_metadata_user_presave(UserInterface $user) {
  // Ensure that administrators cannot have the podficcer role.
  // Allowing both roles means that when an admin edits another users work
  // errors with series links occur because restrictions that shouldn't
  // apply to admins are applied.
  $is_admin = FALSE;
  $is_podficcer = FALSE;
  $podfic_role_id = "";

  /** @var \Drupal\user\Entity\Role $role */
  foreach ($user->get('roles')->referencedEntities() as $role) {
    if ($role->isAdmin()) {
      $is_admin = TRUE;
    }

    if ($role->label() === "Podficcer") {
      $is_podficcer = TRUE;
      $podfic_role_id = $role->id();
    }
  }

  if ($is_admin && $is_podficcer) {
    $user->removeRole($podfic_role_id);
    \Drupal::messenger()->addWarning(t('Administrators cannot have the Podficcer role, the role has been removed.'));
  }
}

/**
 * Fetches the reader_name of the currently logged in user.
 */
function propagate_metadata_get_user_tag(string $field_name): EntityInterface|null {
  $user = User::load(\Drupal::currentUser()->id());
  $terms = $user->get($field_name)->referencedEntities();

  return count($terms) > 0 ? $terms[0] : NULL;
}

/**
 * Adds a tag to the default values list of a form field.
 */
function propagate_metadata_fill_default_form_value(&$form, $fieldname, $tag) {
  // Handle both default autocomplete and tagify autocomplete.
  if (isset($form[$fieldname]['widget']['target_id'])) {
    $form[$fieldname]['widget']['target_id']['#default_value'][] = $tag;
  } else {
    $form[$fieldname]['widget']['#default_value'][] = $tag;
  }
}

/**
 * Updates the metadata of all of the series/collections that a work is a member of.
 */
function propagate_metadata_update_all_collections(NodeInterface $work, int $updated_duration_seconds = 0, bool $work_deleted = FALSE) {
  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  foreach ($work->get('field_series')->referencedEntities() as $series) {
    $work_ids = propagate_metadata_works_in_collection_query($series)
      ->condition('nid', [$work->id()], 'NOT IN')
      ->execute();
    $works = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($work_ids);
    if (!$work_deleted) {
      $works[] = $work;
    }

    if ($work->getType() === "work") {
      $utils->setCollectionMetadata($series, $works, updated_work_id: $work->id(), updated_work_duration_seconds: $updated_duration_seconds);
    } elseif ($work->getType() === "legacy_work") {
      $utils->setCollectionMetadata($series, $works);
    }
  }
}

/**
 * Builds a query to fetch all works linked to a collection that the logged in user can access.
 */
function propagate_metadata_works_in_collection_query(EntityInterface $collection): QueryInterface {
  return \Drupal::entityQuery('node')
    ->condition('type', 'work')
    ->condition('field_series.entity:node.nid', $collection->id())
    ->accessCheck(TRUE);
}

/**
 * Calculates the duration of a work from the files attached to it.
 *
 * @param \Drupal\node\NodeInterface $work
 *   The work to calculate a new duration for.
 *
 * @return int
 *   Returns the new duration in seconds.
 */
function propagate_metadata_set_duration(NodeInterface $work): int {
  $duration = 0;

  foreach ($work->get("field_mp3_files")->referencedEntities() as $media) {
    $use_for_duration = $media->get("field_use_for_duration")[0] ?? NULL;
    if (empty($use_for_duration)) {
      continue;
    }
    $use_for_duration = $use_for_duration->value === "1";
    if (!$use_for_duration) {
      continue;
    }

    $media_duration = $media->get("field_duration_seconds")[0] ?? NULL;
    if (!empty($media_duration)) {
      $duration += $media_duration->value;
    }
  }

  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  $duration_interval = $utils->secondsToDateInterval($duration);
  $work->set('field_duration', ['duration' => $duration_interval, 'seconds' => $duration]);
  return $duration;
}
