<?php

/**
 * @file
 * Contains propogate_metadata.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 */
function propagate_metadata_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Prefill reader/curator field on node creation.
  $reader_name = propagate_metadata_get_user_tag('field_reader_name');
  if ($reader_name !== NULL and
      in_array($form_id, ['node_work_form', 'node_playlist_form', 'node_reader_collection_form'])
    ) {
    propagate_metadata_fill_default_form_value($form, 'field_reader', $reader_name);
  }

  $curator_name = propagate_metadata_get_user_tag('field_curator_name');
  if ($curator_name !== NULL and $form_id == 'node_rec_list_form') {
    propagate_metadata_fill_default_form_value($form, 'field_curator', $reader_name);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for nodes.
 */
function propagate_metadata_node_presave(NodeInterface $node) {
  if ($node->getType() === "work") {
    propagate_metadata_set_duration($node);
  }

  if (in_array($node->getType(), ["work", "legacy_work", "playlist", "reader_collection"])) {
    propagate_metadata_update_all_collections($node);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for nodes.
 */
function propagate_metadata_node_delete(NodeInterface $node) {
  if (in_array($node->getType(), ["work", "legacy_work", "playlist", "reader_collection"])) {
    propagate_metadata_update_all_collections($node, TRUE);
  }
}

/**
 * Fetches the reader_name of the currently logged in user.
 */
function propagate_metadata_get_user_tag(string $field_name): EntityInterface|null {
  $user = User::load(\Drupal::currentUser()->id());
  $terms = $user->get($field_name)->referencedEntities();

  return count($terms) > 0 ? $terms[0] : NULL;
}

/**
 * Adds a tag to the default values list of a form field.
 */
function propagate_metadata_fill_default_form_value(&$form, $fieldname, $tag) {
  // Handle both default autocomplete and tagify autocomplete.
  if (isset($form[$fieldname]['widget']['target_id'])) {
    $form[$fieldname]['widget']['target_id']['#default_value'][] = $tag;
  } else {
    $form[$fieldname]['widget']['#default_value'][] = $tag;
  }
}

/**
 * Updates the metadata of all of the series/collections that a work is a member of.
 */
function propagate_metadata_update_all_collections(NodeInterface $node, bool $node_deleted = FALSE) {
  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  $series = [];
  $reader_collections = [];
  $rec_lists = [];

  if ($node->getType() === "work") {
    $series = $node->get('field_series')->referencedEntities();
    $reader_collections = $node->get('field_reader_collections')->referencedEntities();
  }

  $rec_list_ids = \Drupal::entityQuery('node')
    ->condition('type', 'rec_list')
    ->condition('field_works', [$node->id()], 'IN')
    ->accessCheck(TRUE)
    ->execute();
  $rec_lists = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($rec_list_ids);

  if (!empty($series)) {
    $series = $series[0];
    $series_works = propagate_metadata_get_collection_works($series, $node, 'field_series.entity:node.nid');
    if (!$node_deleted) {
      $series_works[] = $node;
    }
    $utils->setCollectionMetadata($series, $series_works);
  }

  foreach ($reader_collections as $collection) {
    $collection_works = propagate_metadata_get_collection_works($collection, $node, 'field_reader_collections.entity:node.nid');
    if (!$node_deleted) {
      $collection_works[] = $node;
    }
    $utils->setCollectionMetadata($collection, $collection_works);
  }

  foreach ($rec_lists as $rec_list) {
    $rec_list_works = $rec_list->get('field_works')->referencedEntities();

    $node_key = NULL;
    foreach ($rec_list_works as $key => $value) {
      if ($value->id() == $node->id()) {
        $node_key = $key;
        break;
      }
    }
    if (!$node_deleted) {
      $rec_list_works[$node_key] = $node;
    }

    $utils->setCollectionMetadata($rec_list, $rec_list_works);
  }
}

/**
 * Fetches all of the works in a collection.
 */
function propagate_metadata_get_collection_works(EntityInterface $collection, NodeInterface $work, string $field_condition): array {
  $work_ids = \Drupal::entityQuery('node')
    ->condition('type', 'work')
    ->condition($field_condition, $collection->id())
    ->condition('nid', [$work->id()], 'NOT IN')
    ->accessCheck(TRUE)
    ->execute();
  return \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($work_ids);
}

/**
 * Calculates the duration of a work from the files attached to it.
 */
function propagate_metadata_set_duration(NodeInterface $work) {
  $duration = 0;

  foreach ($work->get("field_mp3_files")->referencedEntities() as $media) {
    $use_for_duration = $media->get("field_use_for_duration")[0] ?? NULL;
    if (empty($use_for_duration)) {
      continue;
    }
    $use_for_duration = $use_for_duration->value === "1";
    if (!$use_for_duration) {
      continue;
    }

    $media_duration = $media->get("field_duration_seconds")[0] ?? NULL;
    if (!empty($media_duration)) {
      $duration += $media_duration->value;
    }
  }

  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  $duration_interval = $utils->secondsToDateInterval($duration);
  $work->field_duration = ['duration' => $duration_interval, 'seconds' => $duration];
}
