<?php

/**
 * @file
 * Contains propogate_metadata.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 */
function propagate_metadata_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Prefill reader/curator field on node creation.
  $reader_name = propagate_metadata_get_user_tag('field_reader_name');
  if ($reader_name !== NULL and
      in_array($form_id, ['node_work_form', 'node_playlist_form', 'node_reader_collection_form'])
    ) {
    propagate_metadata_fill_default_form_value($form, 'field_reader', $reader_name);
  }

  $curator_name = propagate_metadata_get_user_tag('field_curator_name');
  if ($curator_name !== NULL and $form_id == 'node_rec_list_form') {
    propagate_metadata_fill_default_form_value($form, 'field_curator', $reader_name);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for nodes.
 */
function propagate_metadata_node_presave(NodeInterface $node) {
  if (in_array($node->getType(), ["work", "legacy_work", "playlist", "reader_collection"])) {
    propagate_metadata_update_all_collections($node);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for nodes.
 */
function propagate_metadata_node_delete(NodeInterface $node) {
  if (in_array($node->getType(), ["work", "legacy_work", "playlist", "reader_collection"])) {
    propagate_metadata_update_all_collections($node, TRUE);
  }
}

/**
 * Fetches the reader_name of the currently logged in user.
 */
function propagate_metadata_get_user_tag(string $field_name): EntityInterface|null {
  $user = User::load(\Drupal::currentUser()->id());
  $terms = $user->get($field_name)->referencedEntities();

  return count($terms) > 0 ? $terms[0] : NULL;
}

/**
 * Adds a tag to the default values list of a form field.
 */
function propagate_metadata_fill_default_form_value(&$form, $fieldname, $tag) {
  // Handle both default autocomplete and tagify autocomplete.
  if (isset($form[$fieldname]['widget']['target_id'])) {
    $form[$fieldname]['widget']['target_id']['#default_value'][] = $tag;
  } else {
    $form[$fieldname]['widget']['#default_value'][] = $tag;
  }
}

/**
 * Updates the metadata of all of the series/collections that a work is a member of.
 */
function propagate_metadata_update_all_collections(NodeInterface $node, bool $node_deleted = FALSE) {
  $series = [];
  $reader_collections = [];
  $rec_lists = [];

  if ($node->getType() === "work") {
    $series = $node->get('field_series')->referencedEntities();
    $reader_collections = $node->get('field_reader_collections')->referencedEntities();
  }

  $rec_list_ids = \Drupal::entityQuery('node')
    ->condition('type', 'rec_list')
    ->condition('field_works', [$node->id()], 'IN')
    ->accessCheck(TRUE)
    ->execute();
  $rec_lists = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($rec_list_ids);

  if (!empty($series)) {
    $series = $series[0];
    $series_works = propagate_metadata_get_collection_works($series, $node, 'field_series.entity:node.nid');
    if (!$node_deleted) {
      $series_works[] = $node;
    }
    propagate_metadata_set_metadata($series, $series_works);
  }

  foreach ($reader_collections as $collection) {
    $collection_works = propagate_metadata_get_collection_works($collection, $node, 'field_reader_collections.entity:node.nid');
    if (!$node_deleted) {
      $collection_works[] = $node;
    }
    propagate_metadata_set_metadata($collection, $collection_works);
  }

  foreach ($rec_lists as $rec_list) {
    $rec_list_works = $rec_list->get('field_works')->referencedEntities();

    $node_key = NULL;
    foreach ($rec_list_works as $key => $value) {
      if ($value->id() == $node->id()) {
        $node_key = $key;
        break;
      }
    }
    if (!$node_deleted) {
      $rec_list_works[$node_key] = $node;
    }

    propagate_metadata_set_metadata($rec_list, $rec_list_works);
  }
}

/**
 * Fetches all of the works in a collection.
 */
function propagate_metadata_get_collection_works(EntityInterface $collection, NodeInterface $work, string $field_condition): array {
  $work_ids = \Drupal::entityQuery('node')
    ->condition('type', 'work')
    ->condition($field_condition, $collection->id())
    ->condition('nid', [$work->id()], 'NOT IN')
    ->accessCheck(TRUE)
    ->execute();
  return \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($work_ids);
}

/**
 * Sets the metadata of a series/collection.
 */
function propagate_metadata_set_metadata(NodeInterface $collection, array $works) {
  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  $authors = [];
  $readers = [];
  $fandoms = [];
  $relationships = [];
  $ratings = [];
  $categories = [];
  $format_info = [];
  $languages = [];
  $duration = 0;

  foreach ($works as $work) {
    $authors = array_merge($authors, $work->get('field_author')->referencedEntities());
    $readers = array_merge($readers, $work->get('field_reader')->referencedEntities());
    $fandoms = array_merge($fandoms, $work->get('field_fandom2')->referencedEntities());
    $relationships = array_merge($relationships, $work->get('field_relationship')->referencedEntities());
    $ratings = array_merge($ratings, $work->get('field_rating')->referencedEntities());
    $format_info = array_merge($format_info, $work->get('field_format')->referencedEntities());

    if ($work->hasField('field_category')) {
      $categories = array_merge($categories, $work->get('field_category')->referencedEntities());
    }

    $lang_key = $work->hasField('field_language') ? 'field_language' : 'field_languages';
    $languages = array_merge($languages, $work->get($lang_key)->referencedEntities());

    if ($work->hasField('field_duration')) {
      $found = FALSE;
      foreach ($work->get('field_duration') as $duration_field) {
        $duration += $duration_field->seconds;
        $found = TRUE;
        break;
      }

      // If a legacy work does not have a duration set, calculate it from
      // the length tag.
      if (!$found && $work->getType() == 'legacy_work') {
        foreach ($work->get('field_length')->referencedEntities() as $length_tag) {
          $work_duration = $utils->convertLengthRangeToDuration($length_tag);
          if (!empty($work_duration)) {
            $duration += $work_duration;
            break;
          }
        }
      }
    }
  }

  $authors = $utils->removeDuplicateEntities($authors);
  $readers = $utils->removeDuplicateEntities($readers);
  $fandoms = $utils->removeDuplicateEntities($fandoms);
  $relationships = $utils->removeDuplicateEntities($relationships);
  $ratings = $utils->removeDuplicateEntities($ratings);
  $format_info = $utils->removeDuplicateEntities($format_info);
  $categories = $utils->removeDuplicateEntities($categories);
  $languages = $utils->removeDuplicateEntities($languages);

  // TODO: Rec lists can have works with a rating of NULL. Will need to decide if that
  // has priority
  $rating_value = [
    "General" => 0,
    "Teen and up" => 1,
    "Mature" => 2,
    "Explicit" => 3,
    "Not rated" => 4,
  ];

  $rating = NULL;
  foreach ($ratings as $r) {
    if ($rating === NULL or
        $rating_value[$rating->name->value] < $rating_value[$r->name->value]
      ) {
      $rating = $r;
    }
  }

  $collection->set('field_author', $authors);
  $collection->set('field_reader', $readers);
  $collection->set('field_fandom2', $fandoms);
  $collection->set('field_relationship', $relationships);
  $collection->set('field_rating', [$rating]);
  $collection->set('field_category', $categories);
  $collection->set('field_format', $format_info);
  $collection->set('field_languages', $languages);
  $duration_interval = $utils->secondsToDateInterval($duration);
  $collection->field_duration = ['duration' => $duration_interval, 'seconds' => $duration];
  $collection->save();
}
