<?php

/**
 * @file
 * Contains aa_gin.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\TermInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_page_attachments().
 */
function aa_gin_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'aa_gin/disable-title-nowrap';

  $route = \Drupal::routeMatch()->getRouteName();
  if (in_array($route, [
    "node.add", "node.add_page", "entity.node.edit_form",
    "entity.node.delete_form", "entity.user.canonical",
  ])) {
    $attachments['#attached']['library'][] = 'aa_gin/content-form';
  }
}

/**
 * Implements hook_form_alter().
 */
function aa_gin_form_alter(&$form, $_, $form_id) {
  if (in_array($form_id, ['node_work_form', 'node_work_edit_form'])) {
    aa_gin_insert_series_creation_fields($form);
  }

  if (in_array($form_id, ['node_work_form', 'node_playlist_form'])) {
    aa_gin_prefill_reader($form);
  }

  if (in_array($form_id, [
    'taxonomy_term_fandom_form',
    'taxonomy_term_relationship_form',
    'taxonomy_term_author_form',
    'taxonomy_term_reader_form',
    'taxonomy_term_language_form',
  ])) {
    aa_gin_protect_taxonomy_form($form);
  }

  if (in_array($form_id, ['user_form'])) {
    aa_gin_protect_user_form($form);
  }
}

/**
 * Alters the node creation form to insert the series creation fields.
 *
 * Also ensures that a custom submit handler that correctly handles
 * input to those fields is added.
 */
function aa_gin_insert_series_creation_fields(array &$form) {
  $series_weight = $form['field_series']['#weight'];

  $form['create_series'] = [
    '#type' => 'checkbox',
    '#title' => 'Create new series',
    '#weight' => $series_weight + 1,
    '#group' => 'group_series_and_collections',
  ];

  $form['new_series_name'] = [
    '#type' => 'textfield',
    '#title' => 'New series name',
    '#weight' => $series_weight + 2,
    '#group' => 'group_series_and_collections',
    '#states' => [
      'visible' => [':input[name="create_series"]' => ['checked' => TRUE]],
    ],
  ];

  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'aa_gin_node_form_submit';
    }
  }

  $form['#attached']['library'][] = 'aa_gin/add-new-tag';
}

/**
 * Ensures the default for the owner & reader fields is set to the current user.
 *
 * If the current user does not have an assigned reader tag,
 * this will do nothing.
 */
function aa_gin_prefill_reader(array &$form) {
  $current_user = User::load(\Drupal::currentUser()->id());
  $reader_name = array_first($current_user->get('field_reader_name')->referencedEntities());

  if ($reader_name) {
    aa_gin_fill_default_form_value($form, 'field_reader', $reader_name);
    aa_gin_fill_default_form_value($form, 'field_owner', $reader_name);
  }
}

/**
 * Adds a tag to the default values list of a form field.
 *
 * Handles both the default entity autocomplete & the
 * tagify entity autocomplete.
 */
function aa_gin_fill_default_form_value(array &$form, string $field_name, TermInterface $tag) {
  if (isset($form[$field_name]['widget']['target_id'])) {
    $form[$field_name]['widget']['target_id']['#default_value'][] = $tag;
  } else {
    $form[$field_name]['widget']['#default_value'][] = $tag;
  }
}

/**
 * Custom submit handler for node work forms.
 *
 * If the create_series checkbox is ticked and a new series name is provided,
 * this submit handler creates that new series and links the current work to
 * it.
 */
function aa_gin_node_form_submit(array $form, FormStateInterface $form_state) {
  $series_title = $form['new_series_name']['#value'];
  if (!$form['create_series']['#checked'] || empty($series_title)) {
    return;
  }

  $nid = $form_state->getformObject()->getEntity()->id();
  $series = Node::create([
    'type' => 'playlist',
    'title' => $series_title,
    'field_works_series' => $nid,
  ]);
  $series->save();

  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');
  $work = Node::load($nid);

  $utils->setCollectionMetadata($series, [$work]);
}

/**
 * Alters the taxonomy form to ensure non-admins cannot edit protected fields.
 */
function aa_gin_protect_taxonomy_form(array &$form) {
  /** @var \Drupal\user\UserInterface $user */
  $user = User::load(\Drupal::currentUser()->id());
  if ($user->hasRole('administrator')) {
    return;
  }

  $form['status']['#access'] = FALSE;
  $form['relations']['#access'] = FALSE;
  $form['revision_information']['#access'] = FALSE;
}

/**
 * Alters the user form to ensure non-admins cannot edit protected fields.
 */
function aa_gin_protect_user_form(array &$form) {
  /** @var \Drupal\user\UserInterface $user */
  $user = User::load(\Drupal::currentUser()->id());
  if ($user->hasRole('administrator')) {
    return;
  }

  $form['field_cover_artist_name']['#access'] = FALSE;
  $form['field_reader_name']['#access'] = FALSE;
  $form['field_author_name']['#access'] = FALSE;
  $form['contact']['#access'] = FALSE;
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function aa_gin_inline_entity_form_table_fields_alter(&$fields, $context) {
  if ($context['field_name'] === 'field_mp3_files') {
    unset($fields['label']);

    $fields['field_media_audio_file'] = [
      'type' => 'field',
      'label' => t('File'),
      'weight' => 1,
    ];

    $fields['field_chapter_label'] = [
      'type' => 'field',
      'label' => t('Chapter label'),
      'weight' => 2,
    ];

    $fields['field_use_for_duration'] = [
      'type' => 'field',
      'label' => t('Use for duration?'),
      'weight' => 3,
    ];
  }

  if ($context['field_name'] === 'field_other_files') {
    unset($fields['label']);

    $fields['field_media_file'] = [
      'type' => 'field',
      'label' => t('File'),
      'weight' => 0,
    ];

    $fields['field_file_label'] = [
      'type' => 'field',
      'label' => t('File label'),
      'weight' => 1,
    ];
  }
}
