<?php

/**
 * @file
 * Contains aa_gin.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_page_attachments().
 */
function aa_gin_page_attachments(array &$attachments) {
  $route = \Drupal::routeMatch()->getRouteName();
  if (in_array($route, ["node.add", "node.add_page", "entity.node.edit_form", "entity.node.delete_form"])) {
    $attachments['#attached']['library'][] = 'aa_gin/content-form';
  }
}

/**
 * Implements hook_field_group_form_process_alter().
 */
function aa_gin_field_group_form_process_alter(array &$element, &$group, &$rendering_object) {
  if (in_array($rendering_object['#form_id'], ['node_work_form', 'node_work_edit_form'])) {
    $series_weight = $rendering_object['field_series']['#weight'];

    $rendering_object['field_festival']['#weight'] = $series_weight + 3;
  }
}

/**
 * Implements hook_form_alter().
 */
function aa_gin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_work_form', 'node_work_edit_form'])) {
    // Insert series creation fields.
    $series_weight = $form['field_series']['#weight'];

    $form['create_series'] = [
      '#type' => 'checkbox',
      '#title' => 'Create new series',
      '#weight' => $series_weight + 1,
      '#group' => 'group_series_and_collections',
    ];

    $form['new_series_name'] = [
      '#type' => 'textfield',
      '#title' => 'New series name',
      '#weight' => $series_weight + 2,
      '#group' => 'group_series_and_collections',
      '#states' => [
        'visible' => [':input[name="create_series"]' => ['checked' => TRUE]],
      ],
    ];

    // Add custom submit handler.
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'aa_gin_form_submit';
      }
    }

    $form['#attached']['library'][] = 'aa_gin/add-new-tag';
    return;
  }

  if (in_array($form_id, [
    'taxonomy_term_fandom_form',
    'taxonomy_term_relationship_form',
    'taxonomy_term_author_form',
    'taxonomy_term_reader_form',
    'taxonomy_term_language_form',
  ])) {
    $user = \Drupal::entityTypeManager()->getStorage('user')->load(\Drupal::currentUser()->id());

    // If user is not admin, remove additional taxonomy term form widgets.
    if (!$user->hasRole('administrator')) {
      $form['relations']['#access'] = FALSE;
      $form['revision_information']['#access'] = FALSE;
    }
    return;
  }
}

/**
 * Custom submit handler for node work forms.
 */
function aa_gin_form_submit(array $form, FormStateInterface $form_state) {
  $series_title = $form['new_series_name']['#value'];
  if (!$form['create_series']['#checked'] || empty($series_title)) {
    return;
  }

  $nid = $form_state->getformObject()->getEntity()->id();
  $series = Node::create([
    'type' => 'playlist',
    'title' => $series_title,
    'field_works_series' => $nid,
  ]);
  $series->save();

  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');
  $work = \Drupal::entityTypeManager()->getStorage('node')->load($nid);

  $utils->setCollectionMetadata($series, [$work]);
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function aa_gin_inline_entity_form_table_fields_alter(&$fields, $context) {
  if ($context['field_name'] === 'field_mp3_files') {
    unset($fields['label']);

    $fields['field_media_audio_file'] = [
      'type' => 'field',
      'label' => t('File'),
      'weight' => 1,
    ];

    $fields['field_chapter_label'] = [
      'type' => 'field',
      'label' => t('Chapter label'),
      'weight' => 2,
    ];

    $fields['field_use_for_duration'] = [
      'type' => 'field',
      'label' => t('Use for duration?'),
      'weight' => 3,
    ];
  }

  if ($context['field_name'] === 'field_other_files') {
    unset($fields['label']);

    $fields['field_media_file'] = [
      'type' => 'field',
      'label' => t('File'),
      'weight' => 0,
    ];

    $fields['field_file_label'] = [
      'type' => 'field',
      'label' => t('File label'),
      'weight' => 1,
    ];
  }
}
