<?php

/**
 * @file
 * Contains audiofic_archive_rss.module.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\file\Entity\File;
use Drupal\media\MediaInterface;

/**
 * Implements template_preprocess_views_view() for audiofic_archive_rss.
 */
function audiofic_archive_rss_preprocess_views_view_audiofic_archive_rss(&$variables) {
  $options = $variables['view']->style_plugin->options;

  $contextual_filters = $variables['view']->argument;
  // dump($contextual_filters);

  if (count($contextual_filters) > 0) {
    $argument = reset($contextual_filters);
    $argument_type = $argument->options["default_argument_type"];

    $nid = NULL;
    $tid = NULL;

    if ($argument_type === "node") {
      $nid = $argument->argument;
    }

    if ($argument_type === "taxonomy_tid") {
      $tid = $argument->argument;
    }

    $source_node = $nid !== NULL ? \Drupal::entityTypeManager()->getStorage('node')->load($nid) : NULL;
    $source_term = $tid !== NULL ? \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid) : NULL;
    if ($source_node != NULL) {
      $authors = audiofic_archive_rss_fetch_tags($source_node, "field_author");
      $readers = audiofic_archive_rss_fetch_tags($source_node, "field_reader");

      $token_service = \Drupal::token();
      $desc = $token_service->replace(
        $options['contextual_description'],
        ['contextual_filter_node' => $source_node],
        ['clear' => TRUE]
      );

      $variables['contextual_filter'] = 'node';
      $variables['source_node'] = [
        "title" => $source_node->getTitle(),
        "author" => "Read by: $readers | Written by: $authors",
        "cover_url" => audiofic_archive_rss_fetch_cover($source_node),
        "explicit" => audiofic_archive_rss_is_explicit($source_node),
        "description" => $desc,
        "link" => $source_node->toUrl(),
      ];
    } elseif ($source_term !== NULL) {
      $token_service = \Drupal::token();
      $desc = $token_service->replace(
        $options['contextual_description'],
        ['contextual_filter_term' => $source_term],
        ['clear' => TRUE]
      );

      $variables['contextual_filter'] = 'term';
      $variables['source_term'] = [
        "title" => $source_term->name->value,
        "description" => $desc,
        "link" => $source_term->toUrl(),
      ];
    } else {
      $variables['contextual_filter'] = 'none';
    }
  }

  $works = [];
  foreach ($variables['view']->result as $result) {
    $entity = $result->_entity;
    if ($entity->getType() != "work") {
      continue;
    }

    $files = [];
    audiofic_archive_rss_fetch_media_files($entity, $files, $variables['contextual_filter'] !== 'none');

    array_push($works, [
      "title" => $entity->getTitle(),
      "explicit" => audiofic_archive_rss_is_explicit($entity),
      "files" => $files,
      "tags" => audiofic_archive_rss_get_all_tags($entity),
      "cover_url" => audiofic_archive_rss_fetch_cover($entity),
      "link" => $entity->toUrl(),
    ]);
  }

  $variables['options'] = $options;
  $variables['works'] = $works;
}

/**
 * Implements hook_theme() for audiofic_archive_rss.
 */
function audiofic_archive_rss_theme($existing, $type, $theme, $path) {
  return [
    'audiofic_archive_rss' => [
      'template' => 'audiofic_archive_rss',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_token_info().
 */
function audiofic_archive_rss_token_info() {
  return [
    'types' => [
      'contextual-filter-node' => [
        'name' => t('Contextual Filter Node'),
        'description' => t('The node selected by the view contextual filter'),
        'needs-data' => 'contextual_filter_node',
      ],
    ],
    'tokens' => [
      'contextual-filter-node' => [
        'title' => ['name' => t('Title')],
        'tags' => ['name' => t('Tags')],
      ],
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function audiofic_archive_rss_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  if ($type === 'contextual-filter-node' && array_key_exists('contextual_filter_node', $data)) {
    $node = $data['contextual_filter_node'];

    foreach ($tokens as $key => $token) {
      switch ($key) {
        case 'title':
          $replacements[$token] = $node->getTitle();
          break;

        case 'tags':
          $replacements[$token] = audiofic_archive_rss_get_all_tags($node);
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_ENTITY_TYPE_presave() for media.
 */
function audiofic_archive_rss_media_presave(MediaInterface $entity) {
  if ($entity->bundle() == 'mp3_file') {
    if (count($entity->get("field_duration_seconds")) <= 0) {
      $file = File::load($entity->get("field_media_audio_file")[0]->target_id);
      $file_path_on_disk = \Drupal::service('file_system')->realpath($file->getFileUri());

      $getID3 = new \getID3();
      $file_info = $getID3->analyze($file_path_on_disk);
      $duration = round($file_info['playtime_seconds']);

      $entity->set("field_duration_seconds", $duration);
    }
  }
}

/**
 * Fetches the media files from a node and adds them to $files.
 */
function audiofic_archive_rss_fetch_media_files($entity, &$files, bool $sort_by_chapter) {
  $work_files = [];

  if ($entity->hasField("field_mp3_files")) {
    foreach ($entity->get("field_mp3_files")->referencedEntities() as $file) {
      $phys_file = File::load($file->field_media_audio_file[0]->target_id);
      $label = $file->get("field_chapter_label");
      $duration = $file->get("field_duration_seconds");

      $data = [
        "name" => count($label) > 0 ? $label[0]->value : "",
        "file_size" => $phys_file->filesize->value,
        "mime_type" => $phys_file->filemime->value,
        "url" => $phys_file->createFileUrl(),
        "uuid" => $file->uuid(),
        "duration" => count($duration) > 0 ? $duration[0]->value : 0,
        "date_created" => $file->getCreatedTime(),
      ];

      array_push($work_files, $data);
    }
  }

  if ($sort_by_chapter) {
    // To have the chapters of a work appear sequentially in any of
    // our feeds, they need to have sequential publishing dates.
    // Series may be out of order, but they atleast won't be jumbled.
    $date_updated = $entity->getCreatedTime();
    usort($work_files, fn($a, $b) => strcmp($a["name"], $b["name"]));
    $i = 0;
    foreach ($work_files as $file_data) {
      $file_data["date_created"] = $date_updated + $i;
      $i++;
      array_push($files, $file_data);
    }
  } else {
    foreach ($work_files as $file_data) {
      array_push($files, $file_data);
    }
  }
}

/**
 * Fetches the tag names from an entity and truncates them.
 */
function audiofic_archive_rss_fetch_tags($entity, $vocab_name, ?int $truncate_to = NULL) {
  $all_tags = [];
  if ($entity->hasField($vocab_name)) {
    $tags = $entity->get($vocab_name)->referencedEntities();
    foreach ($tags as $tag) {
      array_push($all_tags, $tag->name->value);
    }
  }

  if ($truncate_to !== NULL) {
    if (count($all_tags) > $truncate_to) {
      $all_tags = array_slice($all_tags, 0, $truncate_to);
      $all_tags[$truncate_to - 1] = $all_tags[$truncate_to - 1] . "...";
    }
  }

  return implode(', ', $all_tags);
}

/**
 * Fetches the cover url of a node.
 */
function audiofic_archive_rss_fetch_cover($entity) {
  $cover_field = $entity->get("field_cover")->referencedEntities();
  return count($cover_field) > 0 ? $cover_field[0]->createFileUrl() : NULL;
}

/**
 * Fetches whether or not a node is explicit.
 *
 * Explicit works have a rating of 'Explicit', 'Mature', 'Not Rated'
 * or have a NULL rating.
 */
function audiofic_archive_rss_is_explicit($entity) {
  $rating = $entity->get("field_rating")->referencedEntities();
  return count($rating) < 1 ||
         in_array($rating[0]->name->value, ["Explicit", "Mature", "Not Rated"]);
}

/**
 * Fetches and joins all of the tags on a work.
 */
function audiofic_archive_rss_get_all_tags($entity) {
  $tags = [
    "Warning(s):" => audiofic_archive_rss_fetch_tags($entity, "field_warning"),
    "Fandom(s):" => audiofic_archive_rss_fetch_tags($entity, "field_fandom2", 10),
    "Relationship(s):" => audiofic_archive_rss_fetch_tags($entity, "field_relationship", 10),
    "Category/Categories:" => audiofic_archive_rss_fetch_tags($entity, "field_category"),
    "Format Info:" => audiofic_archive_rss_fetch_tags($entity, "field_format"),
  ];

  $text = [];
  foreach ($tags as $label => $content) {
    if (!empty($content)) {
      array_push($text, "$label $content");
    }
  }

  return implode("\n", $text);
}
