<?php

/**
 * @file
 * Contains audiofic_archive_rss.module.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\file\Entity\File;
use Drupal\media\MediaInterface;

/**
 * Implements template_preprocess_views_view() for audiofic_archive_rss.
 */
function audiofic_archive_rss_preprocess_views_view_audiofic_archive_rss(&$variables) {
  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  $options = $variables['view']->style_plugin->options;

  $token_data = ['view' => $variables['view']];
  $contextual_filters = $variables['view']->argument;

  if (count($contextual_filters) > 0) {
    $argument = reset($contextual_filters);
    $argument_type = $argument->options["default_argument_type"];

    $nid = NULL;
    $tid = NULL;

    // TODO: Figure out if there are more exceptions I should account for (tid on regular view, nid on search view for collections)
    if ($argument_type === "node") {
      $nid = $argument->argument;
    }

    if ($argument_type === "taxonomy_tid") {
      $tid = $argument->argument;
    }

    /** @var \Drupal\node\NodeInterface $source_node */
    $source_node = $nid !== NULL ? \Drupal::entityTypeManager()->getStorage('node')->load($nid) : NULL;
    $source_term = $tid !== NULL ? \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid) : NULL;
    if ($source_node != NULL) {
      $authors = audiofic_archive_rss_fetch_tags($source_node, "field_author");
      $readers = audiofic_archive_rss_fetch_tags($source_node, "field_reader");

      $token_data['contextual_filter_node'] = $source_node;
      $variables['contextual_filter'] = 'node';
      $variables['source_node'] = [
        "author" => "Read by: $readers | Written by: $authors",
        "cover_url" => audiofic_archive_rss_fetch_cover($source_node),
        "explicit" => $utils->isNsfw($source_node),
      ];
    } elseif ($source_term !== NULL) {
      $token_data['contextual_filter_term'] = $source_term;
      $variables['contextual_filter'] = 'term';
    } else {
      $variables['contextual_filter'] = 'none';
    }
  } else {
    $variables['contextual_filter'] = 'none';
  }

  $token_service = \Drupal::token();
  $options['title'] = $token_service->replace($options['title'], $token_data, ['clear' => TRUE]);
  $options['description'] = $token_service->replace($options['description'], $token_data, ['clear' => TRUE]);
  $options['link'] = $token_service->replace($options['link'], $token_data, ['clear' => TRUE]);

  $works = [];
  foreach ($variables['view']->result as $result) {
    $entity = $result->_entity;
    if ($entity->getType() != "work") {
      continue;
    }

    $files = [];
    $override_media_pubdate = $variables['contextual_filter'] !== 'none' && $options['override_media_pubdate'];
    audiofic_archive_rss_fetch_media_files($entity, $files, $override_media_pubdate);

    array_push($works, [
      "title" => $entity->getTitle(),
      "explicit" => $utils->isNsfw($entity),
      "files" => $files,
      "tags" => audiofic_archive_rss_get_all_tags($entity),
      "cover_url" => audiofic_archive_rss_fetch_cover($entity),
      "link" => $entity->toUrl(),
    ]);
  }

  $variables['options'] = $options;
  $variables['works'] = $works;
  $variables['hostname'] = \Drupal::request()->getHost();
}

/**
 * Implements hook_theme() for audiofic_archive_rss.
 */
function audiofic_archive_rss_theme($existing, $type, $theme, $path) {
  return [
    'audiofic_archive_rss' => [
      'template' => 'audiofic_archive_rss',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_token_info().
 */
function audiofic_archive_rss_token_info() {
  return [
    'types' => [
      'contextual-filter-node' => [
        'name' => t('Contextual Filter Node'),
        'description' => t('The node selected by the view contextual filter'),
        'needs-data' => 'contextual_filter_node',
      ],
      'contextual-filter-term' => [
        'name' => t('Contextual Filter Taxonomy Term'),
        'description' => t('The Taxonomy Term selected by the contextual filter'),
        'needs-data' => 'contextual_filter_term',
      ],
      'exposed-filters' => [
        'name' => t('Exposed Filters'),
        'description' => t('The exposed filters currently applied by the user to this view'),
        'needs-data' => 'view',
      ],
    ],
    'tokens' => [
      'contextual-filter-node' => [
        'title' => ['name' => t('Title')],
        'tags' => ['name' => t('Tags')],
        'link' => ['name' => t('Link')],
      ],
      'contextual-filter-term' => [
        'title' => ['name' => t('Title')],
        'link' => ['name' => t('Link')],
      ],
      'exposed-filters' => [
        'top-4-filters' => ['name' => t('The top 4 most important filters applied')],
        'filter-summary' => ['name' => t('A formatted summary of all the filters applied')],
        'spacer' => ['name' => t("Prints a '|' character if any filters are present")],
      ]
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function audiofic_archive_rss_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  if ($type === 'contextual-filter-node' && array_key_exists('contextual_filter_node', $data)) {
    $node = $data['contextual_filter_node'];
    foreach ($tokens as $key => $token) {
      switch ($key) {
        case 'title':
          $replacements[$token] = $node->getTitle();
          break;

        case 'tags':
          $replacements[$token] = audiofic_archive_rss_get_all_tags($node);
          break;

        case 'link':
          $replacements[$token] = $node->toUrl()->toString();
          break;
      }
    }
  }

  if ($type === 'contextual-filter-term' && array_key_exists('contextual_filter_term', $data)) {
    $term = $data['contextual_filter_term'];
    foreach ($tokens as $key => $token) {
      switch ($key) {
        case 'title':
          $replacements[$token] = $term->name->value;
          break;

        case 'link':
          $replacements[$token] = $term->toUrl()->toString();
          break;
      }
    }
  }

  if ($type === 'exposed-filters' && array_key_exists('view', $data)) {
    $filters = $data['view']->filter;
    $filter_data = [];

    $keys = [
      'search_api_fulltext', 'field_completion_status', 'field_rating',
      'field_category', 'field_format', 'field_language', 'field_length',
      'field_warning', 'field_author', 'field_reader', 'field_fandom2',
      'field_relationship',
    ];
    $labels = [
      'search_api_fulltext' => "Search Query",
      'field_completion_status' => "Completion Status",
      'field_rating' => "Rating",
      'field_category' => "Category/Categories",
      'field_format' => "Format Info",
      'field_language' => "Language(s)",
      'field_length' => "Length(s)",
      'field_warning' => "Warning(s)",
      'field_author' => "Author(s)",
      'field_reader' => "Reader(s)",
      'field_fandom2' => "Fandom(s)",
      'field_relationship' => "Relationship(s)",
    ];
    foreach ($keys as $key) {
      if (array_key_exists($key, $filters)) {
        if ($key === 'field_completion_status') {
          // only_complete = On if All is not selected, off if all is selected
          $filter_data[$key] = $filters[$key]->group_info !== "All";
        } else {
          $filter_data[$key] = $filters[$key]->value;
        }
      }
    }

    foreach ($tokens as $key => $token) {
      switch ($key) {
        case 'top-4-filters':
          break;

        case 'filter-summary':
          $formatted = [];
          $max = 50;
          foreach ($filter_data as $key => $value) {
            $str = "";
            if ($key == 'search_api_fulltext') {
              $str = $value;
            } elseif ($key === 'field_completion_status') {
              $str = $value ? "Only complete works" : "";
            } else {
              $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadMultiple($value);
              $terms_str = array_map(fn($t) => $t->name->value, $terms);
              $str = implode(", ", $terms_str);
            }

            // Truncate to $max characters.
            $str = strlen($str) > $max + 3 ? substr($str, 0, $max) . "..." : $str;

            if (!empty($str)) {
              $formatted[] = sprintf("%s: %s", $labels[$key], $str);
            }
          }

          $replacements[$token] = implode("\n", $formatted);
          break;

        case 'spacer':
          if (!empty(array_filter($filter_data))) {
            $replacements[$token] = "|";
          }
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_ENTITY_TYPE_presave() for media.
 */
function audiofic_archive_rss_media_presave(MediaInterface $entity) {
  if ($entity->bundle() == 'mp3_file') {
    if (count($entity->get("field_duration_seconds")) <= 0) {
      $file = File::load($entity->get("field_media_audio_file")[0]->target_id);
      $file_path_on_disk = \Drupal::service('file_system')->realpath($file->getFileUri());

      $getID3 = new \getID3();
      $file_info = $getID3->analyze($file_path_on_disk);
      $duration = round($file_info['playtime_seconds']);

      $entity->set("field_duration_seconds", $duration);
    }
  }
}

/**
 * Fetches the media files from a node and adds them to $files.
 */
function audiofic_archive_rss_fetch_media_files($entity, &$files, bool $sort_by_chapter) {
  $work_files = [];

  if ($entity->hasField("field_mp3_files")) {
    foreach ($entity->get("field_mp3_files")->referencedEntities() as $file) {
      $phys_file = File::load($file->field_media_audio_file[0]->target_id);
      $label = $file->get("field_chapter_label");
      $duration = $file->get("field_duration_seconds");

      $data = [
        "name" => count($label) > 0 ? $label[0]->value : "",
        "file_size" => $phys_file->filesize->value,
        "mime_type" => $phys_file->filemime->value,
        "url" => $phys_file->createFileUrl(),
        "uuid" => $file->uuid(),
        "duration" => count($duration) > 0 ? $duration[0]->value : 0,
        "date_created" => $file->getCreatedTime(),
      ];

      $work_files[] = $data;
    }
  }

  if ($sort_by_chapter) {
    // To have the chapters of a work appear sequentially in any of
    // our feeds, they need to have sequential publishing dates.
    // Series may be out of order, but they atleast won't be jumbled.
    $date_updated = $entity->getCreatedTime();
    usort($work_files, fn($a, $b) => strcmp($a["name"], $b["name"]));
    $i = 0;
    foreach ($work_files as $file_data) {
      $file_data["date_created"] = $date_updated + $i;
      $i++;
      $files[] = $file_data;
    }
  } else {
    foreach ($work_files as $file_data) {
      $files[] = $file_data;
    }
  }
}

/**
 * Fetches the tag names from an entity and truncates them.
 */
function audiofic_archive_rss_fetch_tags($entity, $vocab_name, ?int $truncate_to = NULL) {
  /** @var \Drupal\aa_utils\Service\AudioficUtils $utils */
  $utils = \Drupal::service('aa_utils.utils');

  $all_tags = [];
  $utils->fetchVocabTerms($entity, $vocab_name, $all_tags);
  $all_tags = array_map(fn ($term) => $term->name->value, $all_tags);

  if ($truncate_to !== NULL) {
    if (count($all_tags) > $truncate_to) {
      $all_tags = array_slice($all_tags, 0, $truncate_to);
      $all_tags[$truncate_to - 1] = $all_tags[$truncate_to - 1] . "...";
    }
  }

  return implode(', ', $all_tags);
}

/**
 * Fetches the cover url of a node.
 */
function audiofic_archive_rss_fetch_cover($entity) {
  $cover_field = $entity->get("field_cover")->referencedEntities();
  return count($cover_field) > 0 ? $cover_field[0]->createFileUrl() : NULL;
}

/**
 * Fetches and joins all of the tags on a work.
 */
function audiofic_archive_rss_get_all_tags($entity) {
  $tags = [
    "Warning(s):" => audiofic_archive_rss_fetch_tags($entity, "field_warning"),
    "Fandom(s):" => audiofic_archive_rss_fetch_tags($entity, "field_fandom2", 10),
    "Relationship(s):" => audiofic_archive_rss_fetch_tags($entity, "field_relationship", 10),
    "Category/Categories:" => audiofic_archive_rss_fetch_tags($entity, "field_category"),
    "Format Info:" => audiofic_archive_rss_fetch_tags($entity, "field_format"),
  ];

  $text = [];
  foreach ($tags as $label => $content) {
    if (!empty($content)) {
      array_push($text, "$label $content");
    }
  }

  return implode("\n", $text);
}
